### ISSUE TITLE
Minimum version of node not met

### ISSUE THREAD

**Issue by Hartsord** [rxseger/homebridge-udp-contactsensor#1]
I'm trying to use your plugin, but I'm getting this error:

WARN engine homebridge-udp-contactsensor@1.0.1: wanted: {"node":">=6.0.0","homebridge":">=0.2.0"} (current: {"node":"4.3.2","npm":"2.14.12"})

I'm using a Raspberry Pi 3, with updated Raspbian.

**Comment by rxseger** [comment]
@Hartsord If you're (or anyone else) is still having this problem, fix is to update Node - like it says you have node v4.3.2 but it requires node v6.0.0 or later. Raspbian Stretch has node v6.7.0 which should work:

```
pi@raspberrypi:~ $ node -v
v6.7.0
```
